# Basic Usage Example
#
# This example shows the simplest way to use the cancel-queued-runs-action
# in a workflow. It will cancel any runs that have been queued for more than
# 24 hours.

name: Basic Cleanup

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write    # Required to cancel workflow runs
  contents: read    # Required to read repository content

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel stale queued runs
        uses: durandtibo/cancel-queued-runs-action@v1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          max_age_hours: 24
