# Custom Permissions Example
#
# This example demonstrates how to use the action with explicit permissions
# and optionally a custom GitHub token. This is useful when you need more
# control over permissions or want to use a token with specific scopes.

name: Cleanup with Custom Permissions

on:
  workflow_dispatch:
    inputs:
      max_age_hours:
        description: 'Maximum age in hours'
        required: true
        default: '48'
        type: number

jobs:
  cleanup:
    runs-on: ubuntu-latest

    # Explicitly declare minimal required permissions
    permissions:
      actions: write    # Required to cancel workflow runs
      contents: read    # Optional but recommended

    steps:
      - name: Cancel stale queued runs
        uses: durandtibo/cancel-queued-runs-action@v1.7
        with:
          # Option 1: Use the default GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Option 2: Use a custom token (uncomment to use)
          # github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

          repo: ${{ github.repository }}
          max_age_hours: ${{ inputs.max_age_hours }}

      - name: Log completion
        run: |
          echo "Cleanup completed"
          echo "Max age threshold: ${{ inputs.max_age_hours }} hours"

# Notes on Custom Tokens:
#
# If using a custom token (CUSTOM_GITHUB_TOKEN), it needs:
# - 'actions:write' scope for canceling runs
# - 'repo' scope if the repository is private
#
# To create a custom token:
# 1. Go to GitHub Settings > Developer settings > Personal access tokens
# 2. Generate new token with required scopes
# 3. Add it as a repository secret
# 4. Reference it in the workflow as shown above
#
# Using a custom token can be useful for:
# - Cross-repository cleanup
# - Organization-wide automation
# - Fine-grained access control
