# Multi-Repository Cleanup Example
#
# This example demonstrates how to clean up queued runs across multiple
# repositories using a matrix strategy. This is useful for organizations
# managing multiple projects.
#
# Requirements:
# - The GITHUB_TOKEN or custom token must have actions:write permission
#   for all listed repositories
# - This workflow should be placed in a central repository

name: Multi-Repository Cleanup

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      max_age_hours:
        description: 'Maximum age in hours for queued runs'
        required: false
        default: '24'

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      # Don't cancel other matrix jobs if one fails
      fail-fast: false
      matrix:
        repo:
          # Add your repositories here in owner/name format
          - owner/repo1
          - owner/repo2
          - owner/repo3

    steps:
      - name: Cancel stale queued runs for ${{ matrix.repo }}
        uses: durandtibo/cancel-queued-runs-action@v1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ matrix.repo }}
          max_age_hours: ${{ github.event.inputs.max_age_hours || 24 }}

      - name: Log completion
        run: echo "Cleanup completed for ${{ matrix.repo }}"
